// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:example/app/controllers/home/home_controller.dart' as prefix1;
import 'package:example/app/controllers/users/user_constroller.dart' as prefix2;
import 'package:karee_inject/src/annotations/controller.dart' as prefix0;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.ControllerReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'HomeController',
            r'.HomeController',
            7,
            0,
            const prefix0.ControllerReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix1.HomeController() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'index': 0,
              r'userService': 0,
              r'userService=': 1,
              r'otherService': 0,
              r'otherService=': 1,
              r'parameterService': 0,
              r'parameterService=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'UserController',
            r'.UserController',
            7,
            1,
            const prefix0.ControllerReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix2.UserController() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'home': 1,
              r'filter': 1,
              r'userService': 0,
              r'userService=': 1
            })
      ],
      null,
      null,
      <Type>[prefix1.HomeController, prefix2.UserController],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'index': (dynamic instance) => instance.index,
        r'userService': (dynamic instance) => instance.userService,
        r'otherService': (dynamic instance) => instance.otherService,
        r'parameterService': (dynamic instance) => instance.parameterService,
        r'home': (dynamic instance) => instance.home,
        r'filter': (dynamic instance) => instance.filter
      },
      {
        r'userService=': (dynamic instance, value) =>
            instance.userService = value,
        r'otherService=': (dynamic instance, value) =>
            instance.otherService = value,
        r'parameterService=': (dynamic instance, value) =>
            instance.parameterService = value
      },
      null,
      [
        const [0, 0, null],
        const [1, 0, null]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
