name: karee_injectable_gen
description: This library is the Karee generator lib, it's used to generate source code according to Karee's project need.
version: 1.0.3+1
homepage: https://github.com/ChamplainLeCode/karee_injectable_gen
repository: https://github.com/ChamplainLeCode/karee_injectable_gen
issue_tracker: https://github.com/ChamplainLeCode/karee_injectable_gen/issues
report_issue: https://github.com/ChamplainLeCode/karee_injectable_gen/issues/new

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  karee_inject: ^1.0.4+1
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.14
  build_runner: any
