import '../extensions.dart';
import 'package:karee_core/karee_core.dart';
import 'package:example/app/services/user_service.dart';

/// Generated by Karee 

extension UserServiceExtension on UserService {
	void init(){
		serverUrl = readConfig('@{server.proxy.url}');
		port = readConfig('@{server.proxy.port}');
		pageSize = readConfig('@{pageable.default.pageSize}');
		username = readConfig('@{security.authorization.username}');
		password = readConfig('@{security.authorization.password}');
		otherService = extensions['OtherService']();
	}
	UserService get self {
		init();
		return this;
	}
}

final _instanceUserService = UserService()..self;
final $extendedUserService = () => _instanceUserService;
