import 'package:example/app/services/other_service.dart';

/// Generated by Karee 

extension OtherServiceExtension on OtherService {
	void init(){
	}
	OtherService get self {
		init();
		return this;
	}
}

final _instanceOtherService = OtherService()..self;
final $extendedOtherService = () => _instanceOtherService;
