import '../extensions_services.dart';
import 'package:example/app/services/other_service.dart';

/// Generated by Karee 

extension OtherServiceExtension on OtherService {
	static late final OtherService? service;
	static bool loaded = false;
	void init(){
		OtherServiceExtension.service = this;
		OtherServiceExtension.loaded = true;
		userService = serviceExtensions['UserService']();
		parameterService = serviceExtensions['ParameterService']();
	}
	OtherService get self {
		init();
		return this;
	}
}

OtherService $extendedOtherService() {
	if(!OtherServiceExtension.loaded){
		OtherService().self;
	}	return OtherServiceExtension.service!;
}