import '../extensions_services.dart';
import 'package:karee_core/karee_core.dart';
import 'package:example/app/services/parameter_service.dart';

/// Generated by Karee 

extension ParameterServiceExtension on ParameterService {
	static late final ParameterService? service;
	static bool loaded = false;
	void init(){
		roles = List.from(readConfig('@{security.authorization.authorities}'));
		ParameterServiceExtension.service = this;
		ParameterServiceExtension.loaded = true;
		userService = serviceExtensions['UserService']();
		otherService = serviceExtensions['OtherService']();
	}
	ParameterService get self {
		init();
		return this;
	}
}

ParameterService $extendedParameterService() {
	if(!ParameterServiceExtension.loaded){
		ParameterService().self;
	}	return ParameterServiceExtension.service!;
}