import '../extensions_services.dart';
import 'package:example/app/controllers/users/user_constroller.dart';

/// Generated by Karee 

extension UserControllerExtension on UserController {
	static late final UserController? service;
	static bool loaded = false;
	void init(){
		UserControllerExtension.service = this;
		UserControllerExtension.loaded = true;
		userService = serviceExtensions['UserService']();
	}
	UserController get self {
		init();
		return this;
	}
}

UserController get $extendedUserController {
	if(!UserControllerExtension.loaded){
		UserController().self;
	}	return UserControllerExtension.service!;
}